// Comprehensive Shopify Theme Store links for 290+ themes
const themeLinks = {
    // Free Official Themes
    'Dawn': 'https://themes.shopify.com/themes/dawn',
    'Sense': 'https://themes.shopify.com/themes/sense',
    'Craft': 'https://themes.shopify.com/themes/craft',
    'Colorblock': 'https://themes.shopify.com/themes/colorblock',
    'Taste': 'https://themes.shopify.com/themes/taste',
    'Crave': 'https://themes.shopify.com/themes/crave',
    'Studio': 'https://themes.shopify.com/themes/studio',
    'Refresh': 'https://themes.shopify.com/themes/refresh',
    'Origin': 'https://themes.shopify.com/themes/origin',
    'Publisher': 'https://themes.shopify.com/themes/publisher',
    'Minimal': 'https://themes.shopify.com/themes/minimal',
    'Debut': 'https://themes.shopify.com/themes/debut',
    'Brooklyn': 'https://themes.shopify.com/themes/brooklyn',
    'Simple': 'https://themes.shopify.com/themes/simple',
    'Supply': 'https://themes.shopify.com/themes/supply',
    'Narrative': 'https://themes.shopify.com/themes/narrative',
    'Express': 'https://themes.shopify.com/themes/express',
    'Boundless': 'https://themes.shopify.com/themes/boundless',
    
    // Premium Official Themes
    'Horizon': 'https://themes.shopify.com/themes/horizon',
    'Savor': 'https://themes.shopify.com/themes/savor',
    'Spotlight': 'https://themes.shopify.com/themes/spotlight',
    'Trade': 'https://themes.shopify.com/themes/trade',
    'Atelier': 'https://themes.shopify.com/themes/atelier',
    'Tinker': 'https://themes.shopify.com/themes/tinker',
    'Heritage': 'https://themes.shopify.com/themes/heritage',
    'Dwell': 'https://themes.shopify.com/themes/dwell',
    'Pitch': 'https://themes.shopify.com/themes/pitch',
    'Fabric': 'https://themes.shopify.com/themes/fabric',
    'Ritual': 'https://themes.shopify.com/themes/ritual',
    'Ride': 'https://themes.shopify.com/themes/ride',
    'Rise': 'https://themes.shopify.com/themes/rise',
    
    // Premium Third-party Themes
    'Prestige': 'https://themes.shopify.com/themes/prestige',
    'Impact': 'https://themes.shopify.com/themes/impact',
    'Impulse': 'https://themes.shopify.com/themes/impulse',
    'Broadcast': 'https://themes.shopify.com/themes/broadcast',
    'Symmetry': 'https://themes.shopify.com/themes/symmetry',
    'Warehouse': 'https://themes.shopify.com/themes/warehouse',
    'Enterprise': 'https://themes.shopify.com/themes/enterprise',
    'Empire': 'https://themes.shopify.com/themes/empire',
    'Focal': 'https://themes.shopify.com/themes/focal',
    'Wonder': 'https://themes.shopify.com/themes/wonder',
    'Hyper': 'https://themes.shopify.com/themes/hyper',
    'Palo Alto': 'https://themes.shopify.com/themes/palo-alto',
    'Reformation': 'https://themes.shopify.com/themes/reformation',
    'Xtra': 'https://themes.shopify.com/themes/xtra',
    'Eurus': 'https://themes.shopify.com/themes/eurus',
    'Pipeline': 'https://themes.shopify.com/themes/pipeline',
    'Shapes': 'https://themes.shopify.com/themes/shapes',
    'Vision': 'https://themes.shopify.com/themes/vision',
    'Stiletto': 'https://themes.shopify.com/themes/stiletto',
    'Motion': 'https://themes.shopify.com/themes/motion',
    'Stretch': 'https://themes.shopify.com/themes/stretch',
    'Expanse': 'https://themes.shopify.com/themes/expanse',
    'Ignite': 'https://themes.shopify.com/themes/ignite',
    'Local': 'https://themes.shopify.com/themes/local',
    'Vessel': 'https://themes.shopify.com/themes/vessel',
    
    // Additional Premium Themes (A-Z)
    'Aesthetic': 'https://themes.shopify.com/themes/aesthetic',
    'Agile': 'https://themes.shopify.com/themes/agile',
    'Aisle': 'https://themes.shopify.com/themes/aisle',
    'Alchemy': 'https://themes.shopify.com/themes/alchemy',
    'Align': 'https://themes.shopify.com/themes/align',
    'Amber': 'https://themes.shopify.com/themes/amber',
    'Andaman': 'https://themes.shopify.com/themes/andaman',
    'Area': 'https://themes.shopify.com/themes/area',
    'Artist': 'https://themes.shopify.com/themes/artist',
    'Ascension': 'https://themes.shopify.com/themes/ascension',
    'Ascent': 'https://themes.shopify.com/themes/ascent',
    'Athens': 'https://themes.shopify.com/themes/athens',
    'Atlantic': 'https://themes.shopify.com/themes/atlantic',
    'Atom': 'https://themes.shopify.com/themes/atom',
    'Aurora': 'https://themes.shopify.com/themes/aurora',
    'Automation': 'https://themes.shopify.com/themes/automation',
    'Avante': 'https://themes.shopify.com/themes/avante',
    'Avatar': 'https://themes.shopify.com/themes/avatar',
    'Avenue': 'https://themes.shopify.com/themes/avenue',
    'Azzel': 'https://themes.shopify.com/themes/azzel',
    'Banjo': 'https://themes.shopify.com/themes/banjo',
    'Barcelona': 'https://themes.shopify.com/themes/barcelona',
    'Baseline': 'https://themes.shopify.com/themes/baseline',
    'Bazaar': 'https://themes.shopify.com/themes/bazaar',
    'Berlin': 'https://themes.shopify.com/themes/berlin',
    'Bespoke': 'https://themes.shopify.com/themes/bespoke',
    'Beyond': 'https://themes.shopify.com/themes/beyond',
    'Be Yours': 'https://themes.shopify.com/themes/be-yours',
    'Blockshop': 'https://themes.shopify.com/themes/blockshop',
    'Blum': 'https://themes.shopify.com/themes/blum',
    'Boost': 'https://themes.shopify.com/themes/boost',
    'Borders': 'https://themes.shopify.com/themes/borders',
    'Boutique': 'https://themes.shopify.com/themes/boutique',
    'Brava': 'https://themes.shopify.com/themes/brava',
    'Bullet': 'https://themes.shopify.com/themes/bullet',
    'California': 'https://themes.shopify.com/themes/california',
    'Cama': 'https://themes.shopify.com/themes/cama',
    'Canopy': 'https://themes.shopify.com/themes/canopy',
    'Capital': 'https://themes.shopify.com/themes/capital',
    'Carbon': 'https://themes.shopify.com/themes/carbon',
    'Cascade': 'https://themes.shopify.com/themes/cascade',
    'Cello': 'https://themes.shopify.com/themes/cello',
    'Champion': 'https://themes.shopify.com/themes/champion',
    'Charge': 'https://themes.shopify.com/themes/charge',
    'Charm': 'https://themes.shopify.com/themes/charm',
    'Chord': 'https://themes.shopify.com/themes/chord',
    'Colors': 'https://themes.shopify.com/themes/colors',
    'Combine': 'https://themes.shopify.com/themes/combine',
    'Concept': 'https://themes.shopify.com/themes/concept',
    'Context': 'https://themes.shopify.com/themes/context',
    'Copenhagen': 'https://themes.shopify.com/themes/copenhagen',
    'Cornerstone': 'https://themes.shopify.com/themes/cornerstone',
    'Creative': 'https://themes.shopify.com/themes/creative',
    'Creator': 'https://themes.shopify.com/themes/creator',
    'Desert': 'https://themes.shopify.com/themes/desert',
    'Digital': 'https://themes.shopify.com/themes/digital',
    'Distinctive': 'https://themes.shopify.com/themes/distinctive',
    'District': 'https://themes.shopify.com/themes/district',
    'Divide': 'https://themes.shopify.com/themes/divide',
    'Divine': 'https://themes.shopify.com/themes/divine',
    'Drop': 'https://themes.shopify.com/themes/drop',
    'Eclipse': 'https://themes.shopify.com/themes/eclipse',
    'Editions': 'https://themes.shopify.com/themes/editions',
    'Effortless': 'https://themes.shopify.com/themes/effortless',
    'Electro': 'https://themes.shopify.com/themes/electro',
    'Elixira': 'https://themes.shopify.com/themes/elixira',
    'Elysian': 'https://themes.shopify.com/themes/elysian',
    'Emerge': 'https://themes.shopify.com/themes/emerge',
    'Emporium': 'https://themes.shopify.com/themes/emporium',
    'Energy': 'https://themes.shopify.com/themes/energy',
    'Envy': 'https://themes.shopify.com/themes/envy',
    'Erickson': 'https://themes.shopify.com/themes/erickson',
    'Essence': 'https://themes.shopify.com/themes/essence',
    'Essentials': 'https://themes.shopify.com/themes/essentials',
    'Etheryx': 'https://themes.shopify.com/themes/etheryx',
    'Exhibit': 'https://themes.shopify.com/themes/exhibit',
    'Expression': 'https://themes.shopify.com/themes/expression',
    'Fame': 'https://themes.shopify.com/themes/fame',
    'Fashionopolism': 'https://themes.shopify.com/themes/fashionopolism',
    'Fetch': 'https://themes.shopify.com/themes/fetch',
    'Flawless': 'https://themes.shopify.com/themes/flawless',
    'Flow': 'https://themes.shopify.com/themes/flow',
    'Flux': 'https://themes.shopify.com/themes/flux',
    'Foodie': 'https://themes.shopify.com/themes/foodie',
    'Forge': 'https://themes.shopify.com/themes/forge',
    'Frame': 'https://themes.shopify.com/themes/frame',
    'Fresh': 'https://themes.shopify.com/themes/fresh',
    'Futurer': 'https://themes.shopify.com/themes/futurer',
    'Gain': 'https://themes.shopify.com/themes/gain',
    'Galleria': 'https://themes.shopify.com/themes/galleria',
    'Gem': 'https://themes.shopify.com/themes/gem',
    'Genie': 'https://themes.shopify.com/themes/genie',
    'Grid': 'https://themes.shopify.com/themes/grid',
    'Habitat': 'https://themes.shopify.com/themes/habitat',
    'Handmade': 'https://themes.shopify.com/themes/handmade',
    'Highlight': 'https://themes.shopify.com/themes/highlight',
    'Honey': 'https://themes.shopify.com/themes/honey',
    'Huge': 'https://themes.shopify.com/themes/huge',
    'Icon': 'https://themes.shopify.com/themes/icon',
    'Igloo': 'https://themes.shopify.com/themes/igloo',
    'Infinity': 'https://themes.shopify.com/themes/infinity',
    'Influence': 'https://themes.shopify.com/themes/influence',
    'Ira': 'https://themes.shopify.com/themes/ira',
    'Iris': 'https://themes.shopify.com/themes/iris',
    'Kairo': 'https://themes.shopify.com/themes/kairo',
    'Keystone': 'https://themes.shopify.com/themes/keystone',
    'Kidu': 'https://themes.shopify.com/themes/kidu',
    'King': 'https://themes.shopify.com/themes/king',
    'Kingdom': 'https://themes.shopify.com/themes/kingdom',
    'Koto': 'https://themes.shopify.com/themes/koto',
    'Label': 'https://themes.shopify.com/themes/label',
    'Launch': 'https://themes.shopify.com/themes/launch',
    'Loft': 'https://themes.shopify.com/themes/loft',
    'Loka': 'https://themes.shopify.com/themes/loka',
    'Lorenza': 'https://themes.shopify.com/themes/lorenza',
    'Lumin': 'https://themes.shopify.com/themes/lumin',
    'Lute': 'https://themes.shopify.com/themes/lute',
    'Luxe': 'https://themes.shopify.com/themes/luxe',
    'Machina': 'https://themes.shopify.com/themes/machina',
    'Madrid': 'https://themes.shopify.com/themes/madrid',
    'Maker': 'https://themes.shopify.com/themes/maker',
    'Mandolin': 'https://themes.shopify.com/themes/mandolin',
    'Maranello': 'https://themes.shopify.com/themes/maranello',
    'Marble': 'https://themes.shopify.com/themes/marble',
    'Masonry': 'https://themes.shopify.com/themes/masonry',
    'Master': 'https://themes.shopify.com/themes/master',
    'Mavon': 'https://themes.shopify.com/themes/mavon',
    'Maya': 'https://themes.shopify.com/themes/maya',
    'Megastore': 'https://themes.shopify.com/themes/megastore',
    'Meka': 'https://themes.shopify.com/themes/meka',
    'Minimalista': 'https://themes.shopify.com/themes/minimalista',
    'Minion': 'https://themes.shopify.com/themes/minion',
    'Mode': 'https://themes.shopify.com/themes/mode',
    'Modular': 'https://themes.shopify.com/themes/modular',
    'Modules': 'https://themes.shopify.com/themes/modules',
    'Mojave': 'https://themes.shopify.com/themes/mojave',
    'Momentum': 'https://themes.shopify.com/themes/momentum',
    'Monaco': 'https://themes.shopify.com/themes/monaco',
    'Monk': 'https://themes.shopify.com/themes/monk',
    'Mono': 'https://themes.shopify.com/themes/mono',
    'Monochrome': 'https://themes.shopify.com/themes/monochrome',
    'Motto': 'https://themes.shopify.com/themes/motto',
    'Multi': 'https://themes.shopify.com/themes/multi',
    'Murmel': 'https://themes.shopify.com/themes/murmel',
    'Neat': 'https://themes.shopify.com/themes/neat',
    'Nexa': 'https://themes.shopify.com/themes/nexa',
    'Next': 'https://themes.shopify.com/themes/next',
    'Nimbus': 'https://themes.shopify.com/themes/nimbus',
    'Noblesse': 'https://themes.shopify.com/themes/noblesse',
    'Noire': 'https://themes.shopify.com/themes/noire',
    'Nordic': 'https://themes.shopify.com/themes/nordic',
    'Normcore': 'https://themes.shopify.com/themes/normcore',
    'North': 'https://themes.shopify.com/themes/north',
    'Nostalgia': 'https://themes.shopify.com/themes/nostalgia',
    'Nova': 'https://themes.shopify.com/themes/nova',
    'Outsiders': 'https://themes.shopify.com/themes/outsiders',
    'Pacific': 'https://themes.shopify.com/themes/pacific',
    'Paper': 'https://themes.shopify.com/themes/paper',
    'Parallax': 'https://themes.shopify.com/themes/parallax',
    'Paris': 'https://themes.shopify.com/themes/paris',
    'Pastarina': 'https://themes.shopify.com/themes/pastarina',
    'Pesto': 'https://themes.shopify.com/themes/pesto',
    'Piano': 'https://themes.shopify.com/themes/piano',
    'Pinnacle': 'https://themes.shopify.com/themes/pinnacle',
    'Polyform': 'https://themes.shopify.com/themes/polyform',
    'Portland': 'https://themes.shopify.com/themes/portland',
    'Praise': 'https://themes.shopify.com/themes/praise',
    'Primavera': 'https://themes.shopify.com/themes/primavera',
    'Providence': 'https://themes.shopify.com/themes/providence',
    'Purely': 'https://themes.shopify.com/themes/purely',
    'Pursuit': 'https://themes.shopify.com/themes/pursuit',
    'Redefine': 'https://themes.shopify.com/themes/redefine',
    'Refine': 'https://themes.shopify.com/themes/refine',
    'Relax': 'https://themes.shopify.com/themes/relax',
    'Release': 'https://themes.shopify.com/themes/release',
    'Responsive': 'https://themes.shopify.com/themes/responsive',
    'Retina': 'https://themes.shopify.com/themes/retina',
    'Retro': 'https://themes.shopify.com/themes/retro',
    'Roam': 'https://themes.shopify.com/themes/roam',
    'Sahara': 'https://themes.shopify.com/themes/sahara',
    'Sampo': 'https://themes.shopify.com/themes/sampo',
    'San Francisco': 'https://themes.shopify.com/themes/san-francisco',
    'Satoshi': 'https://themes.shopify.com/themes/satoshi',
    'Select': 'https://themes.shopify.com/themes/select',
    'Shark': 'https://themes.shopify.com/themes/shark',
    'Shine': 'https://themes.shopify.com/themes/shine',
    'Showcase': 'https://themes.shopify.com/themes/showcase',
    'Showtime': 'https://themes.shopify.com/themes/showtime',
    'Sitar': 'https://themes.shopify.com/themes/sitar',
    'Sleek': 'https://themes.shopify.com/themes/sleek',
    'Soul': 'https://themes.shopify.com/themes/soul',
    'Space': 'https://themes.shopify.com/themes/space',
    'Spark': 'https://themes.shopify.com/themes/spark',
    'Split': 'https://themes.shopify.com/themes/split',
    'Starlite': 'https://themes.shopify.com/themes/starlite',
    'Startup': 'https://themes.shopify.com/themes/startup',
    'Stockholm': 'https://themes.shopify.com/themes/stockholm',
    'Stockmart': 'https://themes.shopify.com/themes/stockmart',
    'Story': 'https://themes.shopify.com/themes/story',
    'Streamline': 'https://themes.shopify.com/themes/streamline',
    'Strong': 'https://themes.shopify.com/themes/strong',
    'StyleScape': 'https://themes.shopify.com/themes/stylescape',
    'Sunrise': 'https://themes.shopify.com/themes/sunrise',
    'Swipe': 'https://themes.shopify.com/themes/swipe',
    'Swiss': 'https://themes.shopify.com/themes/swiss',
    'Sydney': 'https://themes.shopify.com/themes/sydney',
    'Taiga': 'https://themes.shopify.com/themes/taiga',
    'Tailor': 'https://themes.shopify.com/themes/tailor',
    'Takeout': 'https://themes.shopify.com/themes/takeout',
    'Testament': 'https://themes.shopify.com/themes/testament',
    'Tokyo': 'https://themes.shopify.com/themes/tokyo',
    'Toyo': 'https://themes.shopify.com/themes/toyo',
    'Ultra': 'https://themes.shopify.com/themes/ultra',
    
    // Popular Third-party Themes (External)
    'Turbo': 'https://themes.shopify.com/themes/turbo',
    'Shella': 'https://themeforest.net/item/shella-multipurpose-shopify-sections-theme/26480265',
    'Kalles': 'https://themeforest.net/item/kalles-clean-versatile-responsive-shopify-theme/26320622',
    'Ella': 'https://themeforest.net/item/ella-multipurpose-shopify-sections-theme/25691103',
    'Minimog': 'https://themeforest.net/item/minimog-the-high-converting-shopify-theme/27306049',
    'Avone': 'https://themeforest.net/item/avone-multipurpose-shopify-2-theme/31397423',
    'Beauty': 'https://themeforest.net/item/beauty-multipurpose-responsive-shopify-theme/23323125',
    'Shrine': 'https://themeforest.net/item/shrine-multipurpose-shopify-theme/25706945',
    'Hexo': 'https://themeforest.net/item/hexo-responsive-shopify-theme/26939924',
    'Ecomus': 'https://themeforest.net/item/ecomus-ultimate-shopify-theme/40406409',
    'Paradise': 'https://themeforest.net/item/paradise-multipurpose-shopify-theme/27966467',
    'Conrise': 'https://themeforest.net/item/conrise-multipurpose-shopify-theme/29856294',
    'Glozin': 'https://themeforest.net/item/glozin-multipurpose-shopify-theme/30066069',
    'Speedfly': 'https://themeforest.net/item/speedfly-fashion-responsive-shopify-theme/26853712',
    'Revive': 'https://themeforest.net/item/revive-responsive-shopify-theme/25812638',
    'Eyezy': 'https://themeforest.net/item/eyezy-responsive-shopify-theme/29077337',
    'Superstore': 'https://themeforest.net/item/superstore-responsive-shopify-theme/29216939',
    'Ornate': 'https://themeforest.net/item/ornate-responsive-shopify-theme/28442916',
    'Umino': 'https://themeforest.net/item/umino-responsive-shopify-theme/29079988',
    'Simolux': 'https://themeforest.net/item/simolux-responsive-shopify-theme/27879462',
    'Debutify': 'https://debutify.com/',
    'Olivia': 'https://themeforest.net/item/olivia-multipurpose-shopify-theme/25813511',
    'Unsen': 'https://themeforest.net/item/unsen-multipurpose-shopify-theme/29734041',
    'Vogal': 'https://themeforest.net/item/vogal-responsive-shopify-theme/26825303',
    'Gecko': 'https://themeforest.net/item/gecko-multipurpose-responsive-shopify-theme/25875902',
    'Pose': 'https://themeforest.net/item/pose-responsive-shopify-theme/26419132',
    'Fastor': 'https://themeforest.net/item/fastor-multipurpose-responsive-shopify-theme/25673055',
    'Vendy': 'https://themeforest.net/item/vendy-multipurpose-shopify-theme/30145321',
    'Shopiweb': 'https://themeforest.net/item/shopiweb-multipurpose-shopify-theme/29865134',
    'Pandora': 'https://themeforest.net/item/pandora-multipurpose-shopify-theme/28726853',
    'Self Made': 'https://themeforest.net/item/self-made-multipurpose-shopify-theme/30984627',
    'Airn': 'https://themeforest.net/item/airn-multipurpose-shopify-theme/30562481',
    'Boom': 'https://themeforest.net/item/boom-multipurpose-shopify-theme/31215748',
    'Gluck': 'https://themeforest.net/item/gluck-multipurpose-shopify-theme/31644890',
    'Molding': 'https://themeforest.net/item/molding-multipurpose-shopify-theme/32017842',
    'Lemon': 'https://themeforest.net/item/lemon-multipurpose-shopify-theme/32456789',
    'Booster': 'https://boostertheme.com/'
};const axios = require('axios');

// Comprehensive theme patterns for 290+ Shopify themes
const themeFingerprints = {
    // Free Shopify Themes (Official)
    'Dawn': ['color-scheme-1', 'color-scheme-2', '"Dawn"', 'dawn-theme', 'theme-dawn'],
    'Sense': ['sense-theme', '"Sense"', 'predictive-search', 'collection-filters', 'sense--'],
    'Craft': ['craft-theme', '"Craft"', 'collection-hero', 'product-media', 'craft--'],
    'Colorblock': ['colorblock-theme', '"Colorblock"', 'color-block', 'hero-colorblock', 'colorblock--'],
    'Taste': ['taste-theme', '"Taste"', 'hero-taste', 'product-taste', 'taste--'],
    'Crave': ['crave-theme', '"Crave"', 'hero-crave', 'collection-crave', 'crave--'],
    'Studio': ['studio-theme', '"Studio"', 'hero-studio', 'product-studio', 'studio--'],
    'Refresh': ['refresh-theme', '"Refresh"', 'hero-refresh', 'collection-refresh', 'refresh--'],
    'Origin': ['origin-theme', '"Origin"', 'origin--', 'theme-origin', 'hero-origin'],
    'Publisher': ['publisher-theme', '"Publisher"', 'publisher--', 'theme-publisher', 'hero-publisher'],
    'Minimal': ['minimal', '"Minimal"', 'minimal-theme'],
    'Debut': ['site-header', 'product-single', '"Debut"', 'debut-theme'],
    'Brooklyn': ['brooklyn', 'hero-banner', '"Brooklyn"', 'brooklyn-theme'],
    'Simple': ['simple-theme', '"Simple"', 'simple--', 'theme-simple'],
    'Supply': ['supply-theme', '"Supply"', 'supply--', 'theme-supply'],
    'Narrative': ['narrative-theme', '"Narrative"', 'narrative--', 'theme-narrative'],
    'Express': ['express-theme', '"Express"', 'express--', 'theme-express'],
    'Boundless': ['boundless-theme', '"Boundless"', 'boundless--', 'theme-boundless'],
    
    // Premium Shopify Themes (Official)
    'Horizon': ['horizon-theme', '"Horizon"', 'horizon--', 'theme-horizon', 'hero-horizon'],
    'Savor': ['savor-theme', '"Savor"', 'savor--', 'theme-savor', 'hero-savor'],
    'Spotlight': ['spotlight-theme', '"Spotlight"', 'spotlight--', 'theme-spotlight', 'hero-spotlight'],
    'Trade': ['trade-theme', '"Trade"', 'trade--', 'theme-trade', 'hero-trade'],
    'Atelier': ['atelier-theme', '"Atelier"', 'atelier--', 'theme-atelier', 'hero-atelier'],
    'Tinker': ['tinker-theme', '"Tinker"', 'tinker--', 'theme-tinker', 'hero-tinker'],
    'Heritage': ['heritage-theme', '"Heritage"', 'heritage--', 'theme-heritage', 'hero-heritage'],
    'Dwell': ['dwell-theme', '"Dwell"', 'dwell--', 'theme-dwell', 'hero-dwell'],
    'Pitch': ['pitch-theme', '"Pitch"', 'pitch--', 'theme-pitch', 'hero-pitch'],
    'Fabric': ['fabric-theme', '"Fabric"', 'fabric--', 'theme-fabric', 'hero-fabric'],
    'Ritual': ['ritual-theme', '"Ritual"', 'ritual--', 'theme-ritual', 'hero-ritual'],
    'Ride': ['ride-theme', '"Ride"', 'ride--', 'theme-ride', 'hero-ride'],
    'Rise': ['rise-theme', '"Rise"', 'rise--', 'theme-rise', 'hero-rise'],
    
    // Popular Premium Themes (Third-party)
    'Prestige': ['ProductItem__', 'prestige--v4', '"Prestige"', 'prestige-theme', 'theme-prestige'],
    'Impact': ['product-card--blends', 'section-stack', '"Impact"', 'impact-theme', 'theme-impact'],
    'Impulse': ['impulse-theme', '"Impulse"', 'impulse--', 'theme-impulse', 'hero-impulse'],
    'Broadcast': ['broadcast-theme', '"Broadcast"', 'broadcast--', 'theme-broadcast', 'hero-broadcast'],
    'Symmetry': ['symmetry-theme', '"Symmetry"', 'symmetry--', 'theme-symmetry', 'hero-symmetry'],
    'Enterprise': ['enterprise-theme', '"Enterprise"', 'enterprise--', 'theme-enterprise', 'hero-enterprise'],
    'Empire': ['empire-theme', '"Empire"', 'empire--', 'theme-empire', 'hero-empire'],
    'Focal': ['focal-theme', '"Focal"', 'focal--', 'theme-focal', 'hero-focal'],
    'Hyper': ['hyper-theme', '"Hyper"', 'hyper--', 'theme-hyper', 'hero-hyper'],
    'Palo Alto': ['palo-alto-theme', '"Palo Alto"', 'palo-alto--', 'theme-palo-alto', 'hero-palo-alto'],
    'Reformation': ['reformation-theme', '"Reformation"', 'reformation--', 'theme-reformation', 'hero-reformation'],
    'Pipeline': ['pipeline-theme', '"Pipeline"', 'pipeline--', 'theme-pipeline', 'hero-pipeline'],
    'Shapes': ['shapes-theme', '"Shapes"', 'shapes--', 'theme-shapes', 'hero-shapes'],
    'Stiletto': ['stiletto-theme', '"Stiletto"', 'stiletto--', 'theme-stiletto', 'hero-stiletto'],
    'Motion': ['motion-theme', '"Motion"', 'motion--', 'theme-motion', 'hero-motion'],
    'Stretch': ['stretch-theme', '"Stretch"', 'stretch--', 'theme-stretch', 'hero-stretch'],
    'Expanse': ['expanse-theme', '"Expanse"', 'expanse--', 'theme-expanse', 'hero-expanse'],
    'Ignite': ['ignite-theme', '"Ignite"', 'ignite--', 'theme-ignite', 'hero-ignite'],
    'Local': ['local-theme', '"Local"', 'local--', 'theme-local', 'hero-local'],
    
    // Additional Premium Themes (A-Z from Theme Directory)
    'Aesthetic': ['aesthetic-theme', '"Aesthetic"', 'aesthetic--', 'theme-aesthetic'],
    'Agile': ['agile-theme', '"Agile"', 'agile--', 'theme-agile'],
    'Aisle': ['aisle-theme', '"Aisle"', 'aisle--', 'theme-aisle'],
    'Alchemy': ['alchemy-theme', '"Alchemy"', 'alchemy--', 'theme-alchemy'],
    'Align': ['align-theme', '"Align"', 'align--', 'theme-align'],
    'Amber': ['amber-theme', '"Amber"', 'amber--', 'theme-amber'],
    'Andaman': ['andaman-theme', '"Andaman"', 'andaman--', 'theme-andaman'],
    'Area': ['area-theme', '"Area"', 'area--', 'theme-area'],
    'Artist': ['artist-theme', '"Artist"', 'artist--', 'theme-artist'],
    'Ascension': ['ascension-theme', '"Ascension"', 'ascension--', 'theme-ascension'],
    'Ascent': ['ascent-theme', '"Ascent"', 'ascent--', 'theme-ascent'],
    'Athens': ['athens-theme', '"Athens"', 'athens--', 'theme-athens'],
    'Atlantic': ['atlantic-theme', '"Atlantic"', 'atlantic--', 'theme-atlantic'],
    'Atom': ['atom-theme', '"Atom"', 'atom--', 'theme-atom'],
    'Aurora': ['aurora-theme', '"Aurora"', 'aurora--', 'theme-aurora'],
    'Automation': ['automation-theme', '"Automation"', 'automation--', 'theme-automation'],
    'Avante': ['avante-theme', '"Avante"', 'avante--', 'theme-avante'],
    'Avatar': ['avatar-theme', '"Avatar"', 'avatar--', 'theme-avatar'],
    'Avenue': ['avenue-theme', '"Avenue"', 'avenue--', 'theme-avenue'],
    'Azzel': ['azzel-theme', '"Azzel"', 'azzel--', 'theme-azzel'],
    'Banjo': ['banjo-theme', '"Banjo"', 'banjo--', 'theme-banjo'],
    'Barcelona': ['barcelona-theme', '"Barcelona"', 'barcelona--', 'theme-barcelona'],
    'Baseline': ['baseline-theme', '"Baseline"', 'baseline--', 'theme-baseline'],
    'Bazaar': ['bazaar-theme', '"Bazaar"', 'bazaar--', 'theme-bazaar'],
    'Berlin': ['berlin-theme', '"Berlin"', 'berlin--', 'theme-berlin'],
    'Bespoke': ['bespoke-theme', '"Bespoke"', 'bespoke--', 'theme-bespoke'],
    'Beyond': ['beyond-theme', '"Beyond"', 'beyond--', 'theme-beyond'],
    'Be Yours': ['be-yours-theme', '"Be Yours"', 'be-yours--', 'theme-be-yours'],
    'Blockshop': ['blockshop-theme', '"Blockshop"', 'blockshop--', 'theme-blockshop'],
    'Blum': ['blum-theme', '"Blum"', 'blum--', 'theme-blum'],
    'Boost': ['boost-theme', '"Boost"', 'boost--', 'theme-boost'],
    'Borders': ['borders-theme', '"Borders"', 'borders--', 'theme-borders'],
    'Boutique': ['boutique-theme', '"Boutique"', 'boutique--', 'theme-boutique'],
    'Brava': ['brava-theme', '"Brava"', 'brava--', 'theme-brava'],
    'Bullet': ['bullet-theme', '"Bullet"', 'bullet--', 'theme-bullet'],
    'California': ['california-theme', '"California"', 'california--', 'theme-california'],
    'Cama': ['cama-theme', '"Cama"', 'cama--', 'theme-cama'],
    'Canopy': ['canopy-theme', '"Canopy"', 'canopy--', 'theme-canopy'],
    'Capital': ['capital-theme', '"Capital"', 'capital--', 'theme-capital'],
    'Carbon': ['carbon-theme', '"Carbon"', 'carbon--', 'theme-carbon'],
    'Cascade': ['cascade-theme', '"Cascade"', 'cascade--', 'theme-cascade'],
    'Cello': ['cello-theme', '"Cello"', 'cello--', 'theme-cello'],
    'Champion': ['champion-theme', '"Champion"', 'champion--', 'theme-champion'],
    'Charge': ['charge-theme', '"Charge"', 'charge--', 'theme-charge'],
    'Charm': ['charm-theme', '"Charm"', 'charm--', 'theme-charm'],
    'Chord': ['chord-theme', '"Chord"', 'chord--', 'theme-chord'],
    'Colors': ['colors-theme', '"Colors"', 'colors--', 'theme-colors'],
    'Combine': ['combine-theme', '"Combine"', 'combine--', 'theme-combine'],
    'Concept': ['concept-theme', '"Concept"', 'concept--', 'theme-concept'],
    'Context': ['context-theme', '"Context"', 'context--', 'theme-context'],
    'Copenhagen': ['copenhagen-theme', '"Copenhagen"', 'copenhagen--', 'theme-copenhagen'],
    'Cornerstone': ['cornerstone-theme', '"Cornerstone"', 'cornerstone--', 'theme-cornerstone'],
    'Creative': ['creative-theme', '"Creative"', 'creative--', 'theme-creative'],
    'Creator': ['creator-theme', '"Creator"', 'creator--', 'theme-creator'],
    'Desert': ['desert-theme', '"Desert"', 'desert--', 'theme-desert'],
    'Digital': ['digital-theme', '"Digital"', 'digital--', 'theme-digital'],
    'Distinctive': ['distinctive-theme', '"Distinctive"', 'distinctive--', 'theme-distinctive'],
    'District': ['district-theme', '"District"', 'district--', 'theme-district'],
    'Divide': ['divide-theme', '"Divide"', 'divide--', 'theme-divide'],
    'Divine': ['divine-theme', '"Divine"', 'divine--', 'theme-divine'],
    'Drop': ['drop-theme', '"Drop"', 'drop--', 'theme-drop'],
    'Eclipse': ['eclipse-theme', '"Eclipse"', 'eclipse--', 'theme-eclipse'],
    'Editions': ['editions-theme', '"Editions"', 'editions--', 'theme-editions'],
    'Effortless': ['effortless-theme', '"Effortless"', 'effortless--', 'theme-effortless'],
    'Electro': ['electro-theme', '"Electro"', 'electro--', 'theme-electro'],
    'Elixira': ['elixira-theme', '"Elixira"', 'elixira--', 'theme-elixira'],
    'Elysian': ['elysian-theme', '"Elysian"', 'elysian--', 'theme-elysian'],
    'Emerge': ['emerge-theme', '"Emerge"', 'emerge--', 'theme-emerge'],
    'Emporium': ['emporium-theme', '"Emporium"', 'emporium--', 'theme-emporium'],
    'Energy': ['energy-theme', '"Energy"', 'energy--', 'theme-energy'],
    'Envy': ['envy-theme', '"Envy"', 'envy--', 'theme-envy'],
    'Erickson': ['erickson-theme', '"Erickson"', 'erickson--', 'theme-erickson'],
    'Essence': ['essence-theme', '"Essence"', 'essence--', 'theme-essence'],
    'Essentials': ['essentials-theme', '"Essentials"', 'essentials--', 'theme-essentials'],
    'Etheryx': ['etheryx-theme', '"Etheryx"', 'etheryx--', 'theme-etheryx'],
    'Eurus': ['eurus-theme', '"Eurus"', 'eurus--', 'theme-eurus'],
    'Exhibit': ['exhibit-theme', '"Exhibit"', 'exhibit--', 'theme-exhibit'],
    'Expression': ['expression-theme', '"Expression"', 'expression--', 'theme-expression'],
    'Fame': ['fame-theme', '"Fame"', 'fame--', 'theme-fame'],
    'Fashionopolism': ['fashionopolism-theme', '"Fashionopolism"', 'fashionopolism--', 'theme-fashionopolism'],
    'Fetch': ['fetch-theme', '"Fetch"', 'fetch--', 'theme-fetch'],
    'Flawless': ['flawless-theme', '"Flawless"', 'flawless--', 'theme-flawless'],
    'Flow': ['flow-theme', '"Flow"', 'flow--', 'theme-flow'],
    'Flux': ['flux-theme', '"Flux"', 'flux--', 'theme-flux'],
    'Foodie': ['foodie-theme', '"Foodie"', 'foodie--', 'theme-foodie'],
    'Forge': ['forge-theme', '"Forge"', 'forge--', 'theme-forge'],
    'Frame': ['frame-theme', '"Frame"', 'frame--', 'theme-frame'],
    'Fresh': ['fresh-theme', '"Fresh"', 'fresh--', 'theme-fresh'],
    'Futurer': ['futurer-theme', '"Futurer"', 'futurer--', 'theme-futurer'],
    'Gain': ['gain-theme', '"Gain"', 'gain--', 'theme-gain'],
    'Galleria': ['galleria-theme', '"Galleria"', 'galleria--', 'theme-galleria'],
    'Gem': ['gem-theme', '"Gem"', 'gem--', 'theme-gem'],
    'Genie': ['genie-theme', '"Genie"', 'genie--', 'theme-genie'],
    'Grid': ['grid-theme', '"Grid"', 'grid--', 'theme-grid'],
    'Habitat': ['habitat-theme', '"Habitat"', 'habitat--', 'theme-habitat'],
    'Handmade': ['handmade-theme', '"Handmade"', 'handmade--', 'theme-handmade'],
    'Highlight': ['highlight-theme', '"Highlight"', 'highlight--', 'theme-highlight'],
    'Honey': ['honey-theme', '"Honey"', 'honey--', 'theme-honey'],
    'Huge': ['huge-theme', '"Huge"', 'huge--', 'theme-huge'],
    'Icon': ['icon-theme', '"Icon"', 'icon--', 'theme-icon'],
    'Igloo': ['igloo-theme', '"Igloo"', 'igloo--', 'theme-igloo'],
    'Infinity': ['infinity-theme', '"Infinity"', 'infinity--', 'theme-infinity'],
    'Influence': ['influence-theme', '"Influence"', 'influence--', 'theme-influence'],
    'Ira': ['ira-theme', '"Ira"', 'ira--', 'theme-ira'],
    'Iris': ['iris-theme', '"Iris"', 'iris--', 'theme-iris'],
    'Kairo': ['kairo-theme', '"Kairo"', 'kairo--', 'theme-kairo'],
    'Keystone': ['keystone-theme', '"Keystone"', 'keystone--', 'theme-keystone'],
    'Kidu': ['kidu-theme', '"Kidu"', 'kidu--', 'theme-kidu'],
    'King': ['king-theme', '"King"', 'king--', 'theme-king'],
    'Kingdom': ['kingdom-theme', '"Kingdom"', 'kingdom--', 'theme-kingdom'],
    'Koto': ['koto-theme', '"Koto"', 'koto--', 'theme-koto'],
    'Label': ['label-theme', '"Label"', 'label--', 'theme-label'],
    'Launch': ['launch-theme', '"Launch"', 'launch--', 'theme-launch'],
    'Loft': ['loft-theme', '"Loft"', 'loft--', 'theme-loft'],
    'Loka': ['loka-theme', '"Loka"', 'loka--', 'theme-loka'],
    'Lorenza': ['lorenza-theme', '"Lorenza"', 'lorenza--', 'theme-lorenza'],
    'Lumin': ['lumin-theme', '"Lumin"', 'lumin--', 'theme-lumin'],
    'Lute': ['lute-theme', '"Lute"', 'lute--', 'theme-lute'],
    'Luxe': ['luxe-theme', '"Luxe"', 'luxe--', 'theme-luxe'],
    'Machina': ['machina-theme', '"Machina"', 'machina--', 'theme-machina'],
    'Madrid': ['madrid-theme', '"Madrid"', 'madrid--', 'theme-madrid'],
    'Maker': ['maker-theme', '"Maker"', 'maker--', 'theme-maker'],
    'Mandolin': ['mandolin-theme', '"Mandolin"', 'mandolin--', 'theme-mandolin'],
    'Maranello': ['maranello-theme', '"Maranello"', 'maranello--', 'theme-maranello'],
    'Marble': ['marble-theme', '"Marble"', 'marble--', 'theme-marble'],
    'Masonry': ['masonry-theme', '"Masonry"', 'masonry--', 'theme-masonry'],
    'Master': ['master-theme', '"Master"', 'master--', 'theme-master'],
    'Mavon': ['mavon-theme', '"Mavon"', 'mavon--', 'theme-mavon'],
    'Maya': ['maya-theme', '"Maya"', 'maya--', 'theme-maya'],
    'Megastore': ['megastore-theme', '"Megastore"', 'megastore--', 'theme-megastore'],
    'Meka': ['meka-theme', '"Meka"', 'meka--', 'theme-meka'],
    'Minimalista': ['minimalista-theme', '"Minimalista"', 'minimalista--', 'theme-minimalista'],
    'Minion': ['minion-theme', '"Minion"', 'minion--', 'theme-minion'],
    'Mode': ['mode-theme', '"Mode"', 'mode--', 'theme-mode'],
    'Modular': ['modular-theme', '"Modular"', 'modular--', 'theme-modular'],
    'Modules': ['modules-theme', '"Modules"', 'modules--', 'theme-modules'],
    'Mojave': ['mojave-theme', '"Mojave"', 'mojave--', 'theme-mojave'],
    'Momentum': ['momentum-theme', '"Momentum"', 'momentum--', 'theme-momentum'],
    'Monaco': ['monaco-theme', '"Monaco"', 'monaco--', 'theme-monaco'],
    'Monk': ['monk-theme', '"Monk"', 'monk--', 'theme-monk'],
    'Mono': ['mono-theme', '"Mono"', 'mono--', 'theme-mono'],
    'Monochrome': ['monochrome-theme', '"Monochrome"', 'monochrome--', 'theme-monochrome'],
    'Motto': ['motto-theme', '"Motto"', 'motto--', 'theme-motto'],
    'Mr Parker': ['mr-parker-theme', '"Mr Parker"', 'mr-parker--', 'theme-mr-parker'],
    'Multi': ['multi-theme', '"Multi"', 'multi--', 'theme-multi'],
    'Murmel': ['murmel-theme', '"Murmel"', 'murmel--', 'theme-murmel'],
    'Neat': ['neat-theme', '"Neat"', 'neat--', 'theme-neat'],
    'Nexa': ['nexa-theme', '"Nexa"', 'nexa--', 'theme-nexa'],
    'Next': ['next-theme', '"Next"', 'next--', 'theme-next'],
    'Nimbus': ['nimbus-theme', '"Nimbus"', 'nimbus--', 'theme-nimbus'],
    'Noblesse': ['noblesse-theme', '"Noblesse"', 'noblesse--', 'theme-noblesse'],
    'Noire': ['noire-theme', '"Noire"', 'noire--', 'theme-noire'],
    'Nordic': ['nordic-theme', '"Nordic"', 'nordic--', 'theme-nordic'],
    'Normcore': ['normcore-theme', '"Normcore"', 'normcore--', 'theme-normcore'],
    'North': ['north-theme', '"North"', 'north--', 'theme-north'],
    'Nostalgia': ['nostalgia-theme', '"Nostalgia"', 'nostalgia--', 'theme-nostalgia'],
    'Nova': ['nova-theme', '"Nova"', 'nova--', 'theme-nova'],
    'Outsiders': ['outsiders-theme', '"Outsiders"', 'outsiders--', 'theme-outsiders'],
    'Pacific': ['pacific-theme', '"Pacific"', 'pacific--', 'theme-pacific'],
    'Paper': ['paper-theme', '"Paper"', 'paper--', 'theme-paper'],
    'Parallax': ['parallax-theme', '"Parallax"', 'parallax--', 'theme-parallax'],
    'Paris': ['paris-theme', '"Paris"', 'paris--', 'theme-paris'],
    'Pastarina': ['pastarina-theme', '"Pastarina"', 'pastarina--', 'theme-pastarina'],
    'Pesto': ['pesto-theme', '"Pesto"', 'pesto--', 'theme-pesto'],
    'Piano': ['piano-theme', '"Piano"', 'piano--', 'theme-piano'],
    'Pinnacle': ['pinnacle-theme', '"Pinnacle"', 'pinnacle--', 'theme-pinnacle'],
    'Polyform': ['polyform-theme', '"Polyform"', 'polyform--', 'theme-polyform'],
    'Portland': ['portland-theme', '"Portland"', 'portland--', 'theme-portland'],
    'Praise': ['praise-theme', '"Praise"', 'praise--', 'theme-praise'],
    'Primavera': ['primavera-theme', '"Primavera"', 'primavera--', 'theme-primavera'],
    'Providence': ['providence-theme', '"Providence"', 'providence--', 'theme-providence'],
    'Purely': ['purely-theme', '"Purely"', 'purely--', 'theme-purely'],
    'Pursuit': ['pursuit-theme', '"Pursuit"', 'pursuit--', 'theme-pursuit'],
    'Redefine': ['redefine-theme', '"Redefine"', 'redefine--', 'theme-redefine'],
    'Refine': ['refine-theme', '"Refine"', 'refine--', 'theme-refine'],
    'Relax': ['relax-theme', '"Relax"', 'relax--', 'theme-relax'],
    'Release': ['release-theme', '"Release"', 'release--', 'theme-release'],
    'Responsive': ['responsive-theme', '"Responsive"', 'responsive--', 'theme-responsive'],
    'Retina': ['retina-theme', '"Retina"', 'retina--', 'theme-retina'],
    'Retro': ['retro-theme', '"Retro"', 'retro--', 'theme-retro'],
    'Roam': ['roam-theme', '"Roam"', 'roam--', 'theme-roam'],
    'Sahara': ['sahara-theme', '"Sahara"', 'sahara--', 'theme-sahara'],
    'Sampo': ['sampo-theme', '"Sampo"', 'sampo--', 'theme-sampo'],
    'San Francisco': ['san-francisco-theme', '"San Francisco"', 'san-francisco--', 'theme-san-francisco'],
    'Satoshi': ['satoshi-theme', '"Satoshi"', 'satoshi--', 'theme-satoshi'],
    'Select': ['select-theme', '"Select"', 'select--', 'theme-select'],
    'Shark': ['shark-theme', '"Shark"', 'shark--', 'theme-shark'],
    'Shine': ['shine-theme', '"Shine"', 'shine--', 'theme-shine'],
    'Showcase': ['showcase-theme', '"Showcase"', 'showcase--', 'theme-showcase'],
    'Showtime': ['showtime-theme', '"Showtime"', 'showtime--', 'theme-showtime'],
    'Sitar': ['sitar-theme', '"Sitar"', 'sitar--', 'theme-sitar'],
    'Sleek': ['sleek-theme', '"Sleek"', 'sleek--', 'theme-sleek'],
    'Soul': ['soul-theme', '"Soul"', 'soul--', 'theme-soul'],
    'Space': ['space-theme', '"Space"', 'space--', 'theme-space'],
    'Spark': ['spark-theme', '"Spark"', 'spark--', 'theme-spark'],
    'Split': ['split-theme', '"Split"', 'split--', 'theme-split'],
    'Starlite': ['starlite-theme', '"Starlite"', 'starlite--', 'theme-starlite'],
    'Startup': ['startup-theme', '"Startup"', 'startup--', 'theme-startup'],
    'Stockholm': ['stockholm-theme', '"Stockholm"', 'stockholm--', 'theme-stockholm'],
    'Stockmart': ['stockmart-theme', '"Stockmart"', 'stockmart--', 'theme-stockmart'],
    'Story': ['story-theme', '"Story"', 'story--', 'theme-story'],
    'Streamline': ['streamline-theme', '"Streamline"', 'streamline--', 'theme-streamline'],
    'Strong': ['strong-theme', '"Strong"', 'strong--', 'theme-strong'],
    'StyleScape': ['stylescape-theme', '"StyleScape"', 'stylescape--', 'theme-stylescape'],
    'Sunrise': ['sunrise-theme', '"Sunrise"', 'sunrise--', 'theme-sunrise'],
    'Swipe': ['swipe-theme', '"Swipe"', 'swipe--', 'theme-swipe'],
    'Swiss': ['swiss-theme', '"Swiss"', 'swiss--', 'theme-swiss'],
    'Sydney': ['sydney-theme', '"Sydney"', 'sydney--', 'theme-sydney'],
    'Taiga': ['taiga-theme', '"Taiga"', 'taiga--', 'theme-taiga'],
    'Tailor': ['tailor-theme', '"Tailor"', 'tailor--', 'theme-tailor'],
    'Takeout': ['takeout-theme', '"Takeout"', 'takeout--', 'theme-takeout'],
    'Testament': ['testament-theme', '"Testament"', 'testament--', 'theme-testament'],
    'Tokyo': ['tokyo-theme', '"Tokyo"', 'tokyo--', 'theme-tokyo'],
    'Toyo': ['toyo-theme', '"Toyo"', 'toyo--', 'theme-toyo'],
    'Ultra': ['ultra-theme', '"Ultra"', 'ultra--', 'theme-ultra', '.build.css', 'header__menu-item'],
    
    // Popular Third-party Themes (Non-official)
    'Turbo': ['header__logo', 'sticky_nav', '"Turbo"', 'turbo-theme'],
    'Shella': ['shella', '"Shella"', 'shella-theme'],
    'Kalles': ['kalles', '"Kalles"', 'kalles-theme'],
    'Ella': ['ella-theme', '"Ella"', 'ella--', 'theme-ella'],
    'Minimog': ['minimog-theme', '"Minimog"', 'minimog--', 'theme-minimog'],
    'Avone': ['avone-theme', '"Avone"', 'avone--', 'theme-avone'],
    'Beauty': ['beauty-theme', '"Beauty"', 'beauty--', 'theme-beauty'],
    'Shrine': ['shrine-theme', '"Shrine"', 'shrine--', 'theme-shrine'],
    'Hexo': ['hexo-theme', '"Hexo"', 'hexo--', 'theme-hexo'],
    'Ecomus': ['ecomus-theme', '"Ecomus"', 'ecomus--', 'theme-ecomus'],
    'Paradise': ['paradise-theme', '"Paradise"', 'paradise--', 'theme-paradise'],
    'Conrise': ['conrise-theme', '"Conrise"', 'conrise--', 'theme-conrise'],
    'Glozin': ['glozin-theme', '"Glozin"', 'glozin--', 'theme-glozin'],
    'Speedfly': ['speedfly-theme', '"Speedfly"', 'speedfly--', 'theme-speedfly'],
    'Revive': ['revive-theme', '"Revive"', 'revive--', 'theme-revive'],
    'Eyezy': ['eyezy-theme', '"Eyezy"', 'eyezy--', 'theme-eyezy'],
    'Superstore': ['superstore-theme', '"Superstore"', 'superstore--', 'theme-superstore'],
    'Ornate': ['ornate-theme', '"Ornate"', 'ornate--', 'theme-ornate'],
    'Umino': ['umino-theme', '"Umino"', 'umino--', 'theme-umino'],
    'Simolux': ['simolux-theme', '"Simolux"', 'simolux--', 'theme-simolux'],
    'Debutify': ['debutify-theme', '"Debutify"', 'debutify--', 'theme-debutify'],
    'Olivia': ['olivia-theme', '"Olivia"', 'olivia--', 'theme-olivia'],
    'Unsen': ['unsen-theme', '"Unsen"', 'unsen--', 'theme-unsen'],
    'Vogal': ['vogal-theme', '"Vogal"', 'vogal--', 'theme-vogal'],
    'Gecko': ['gecko-theme', '"Gecko"', 'gecko--', 'theme-gecko'],
    'Pose': ['pose-theme', '"Pose"', 'pose--', 'theme-pose'],
    'Fastor': ['fastor-theme', '"Fastor"', 'fastor--', 'theme-fastor'],
    'Vendy': ['vendy-theme', '"Vendy"', 'vendy--', 'theme-vendy'],
    'Shopiweb': ['shopiweb-theme', '"Shopiweb"', 'shopiweb--', 'theme-shopiweb'],
    'Pandora': ['pandora-theme', '"Pandora"', 'pandora--', 'theme-pandora'],
    'Self Made': ['self-made-theme', '"Self Made"', 'self-made--', 'theme-self-made'],
    'Airn': ['airn-theme', '"Airn"', 'airn--', 'theme-airn'],
    'Boom': ['boom-theme', '"Boom"', 'boom--', 'theme-boom'],
    'Gluck': ['gluck-theme', '"Gluck"', 'gluck--', 'theme-gluck'],
    'Molding': ['molding-theme', '"Molding"', 'molding--', 'theme-molding'],
    'Lemon': ['lemon-theme', '"Lemon"', 'lemon--', 'theme-lemon'],
    
    // Additional Popular Themes
    'Warehouse': ['warehouse-theme', '"Warehouse"', 'warehouse--', 'theme-warehouse'],
    'Wonder': ['wonder-theme', '"Wonder"', 'wonder--', 'theme-wonder'],
    'Vision': ['vision-theme', '"Vision"', 'vision--', 'theme-vision'],
    'Xtra': ['xtra-theme', '"Xtra"', 'xtra--', 'theme-xtra'],
    'Vessel': ['vessel-theme', '"Vessel"', 'vessel--', 'theme-vessel'],
    'Booster': ['booster-theme', '"Booster"', 'booster--', 'theme-booster'],
    'Label': ['label-theme', '"Label"', 'label--', 'theme-label'],
    'Blockshop': ['blockshop-theme', '"Blockshop"', 'blockshop--', 'theme-blockshop']
};

// Shopify Theme Store links
const themeLinks = {
    // Free Themes
    'Dawn': 'https://themes.shopify.com/themes/dawn',
    'Sense': 'https://themes.shopify.com/themes/sense',
    'Craft': 'https://themes.shopify.com/themes/craft',
    'Colorblock': 'https://themes.shopify.com/themes/colorblock',
    'Taste': 'https://themes.shopify.com/themes/taste',
    'Crave': 'https://themes.shopify.com/themes/crave',
    'Studio': 'https://themes.shopify.com/themes/studio',
    'Refresh': 'https://themes.shopify.com/themes/refresh',
    
    // Premium Themes
    'Horizon': 'https://themes.shopify.com/themes/horizon',
    'Savor': 'https://themes.shopify.com/themes/savor',
    'Spotlight': 'https://themes.shopify.com/themes/spotlight',
    'Trade': 'https://themes.shopify.com/themes/trade',
    'Vessel': 'https://themes.shopify.com/themes/vessel',
    'Atelier': 'https://themes.shopify.com/themes/atelier',
    'Tinker': 'https://themes.shopify.com/themes/tinker',
    'Heritage': 'https://themes.shopify.com/themes/heritage',
    'Dwell': 'https://themes.shopify.com/themes/dwell',
    'Pitch': 'https://themes.shopify.com/themes/pitch',
    'Fabric': 'https://themes.shopify.com/themes/fabric',
    'Ritual': 'https://themes.shopify.com/themes/ritual',
    'Ride': 'https://themes.shopify.com/themes/ride',
    'Origin': 'https://themes.shopify.com/themes/origin',
    'Publisher': 'https://themes.shopify.com/themes/publisher',
    'Concept': 'https://themes.shopify.com/themes/concept',
    'Sleek': 'https://themes.shopify.com/themes/sleek',
    'Be yours': 'https://themes.shopify.com/themes/be-yours',
    'Prestige': 'https://themes.shopify.com/themes/prestige',
    'Impact': 'https://themes.shopify.com/themes/impact',
    'Impulse': 'https://themes.shopify.com/themes/impulse',
    'Broadcast': 'https://themes.shopify.com/themes/broadcast',
    'Symmetry': 'https://themes.shopify.com/themes/symmetry',
    'Warehouse': 'https://themes.shopify.com/themes/warehouse',
    'Enterprise': 'https://themes.shopify.com/themes/enterprise',
    'Empire': 'https://themes.shopify.com/themes/empire',
    'Focal': 'https://themes.shopify.com/themes/focal',
    'Wonder': 'https://themes.shopify.com/themes/wonder',
    'Hyper': 'https://themes.shopify.com/themes/hyper',
    'Palo Alto': 'https://themes.shopify.com/themes/palo-alto',
    'Reformation': 'https://themes.shopify.com/themes/reformation',
    'Xtra': 'https://themes.shopify.com/themes/xtra',
    'Eurus': 'https://themes.shopify.com/themes/eurus',
    'Pipeline': 'https://themes.shopify.com/themes/pipeline',
    'Shapes': 'https://themes.shopify.com/themes/shapes',
    'Vision': 'https://themes.shopify.com/themes/vision',
    'Stiletto': 'https://themes.shopify.com/themes/stiletto',
    'Motion': 'https://themes.shopify.com/themes/motion',
    'Stretch': 'https://themes.shopify.com/themes/stretch',
    'Expanse': 'https://themes.shopify.com/themes/expanse',
    'Ignite': 'https://themes.shopify.com/themes/ignite',
    'Local': 'https://themes.shopify.com/themes/local',
    
    // Legacy Themes
    'Debut': 'https://themes.shopify.com/themes/debut',
    'Brooklyn': 'https://themes.shopify.com/themes/brooklyn',
    'Minimal': 'https://themes.shopify.com/themes/minimal'
};

function isShopifyStore(html) {
    const indicators = ['Shopify.shop', 'shopify.com', 'window.Shopify', 'cdn.shopify.com'];
    const htmlLower = html.toLowerCase();
    return indicators.some(indicator => htmlLower.includes(indicator.toLowerCase()));
}

function detectTheme(html) {
    const htmlLower = html.toLowerCase();
    let bestMatch = { theme: 'Unknown', score: 0 };
    
    for (const [themeName, patterns] of Object.entries(themeFingerprints)) {
        let score = 0;
        patterns.forEach(pattern => {
            if (htmlLower.includes(pattern.toLowerCase())) {
                score += pattern.includes('"') ? 15 : 5; // Higher weight for exact theme name matches
            }
        });
        
        if (score > bestMatch.score) {
            bestMatch = { theme: themeName, score };
        }
    }
    
    const confidence = bestMatch.score > 0 ? Math.min(Math.round((bestMatch.score / 20) * 100), 100) : 0;
    return {
        theme: bestMatch.score > 5 ? bestMatch.theme : 'Unknown',
        confidence: bestMatch.score > 5 ? confidence : 0
    };
}

module.exports = async (req, res) => {
    // Handle CORS
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    
    if (req.method === 'OPTIONS') {
        res.status(200).end();
        return;
    }

    if (req.method !== 'POST') {
        return res.status(405).json({ 
            success: false, 
            error: 'Method not allowed' 
        });
    }

    const { url } = req.body;

    if (!url) {
        return res.status(400).json({ 
            success: false, 
            error: 'URL is required' 
        });
    }

    try {
        // Normalize URL
        let targetUrl = url.trim();
        if (!targetUrl.startsWith('http://') && !targetUrl.startsWith('https://')) {
            targetUrl = 'https://' + targetUrl;
        }

        console.log(`Analyzing: ${targetUrl}`);

        // Fetch webpage with timeout
        const response = await axios.get(targetUrl, {
            timeout: 10000,
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
            }
        });

        const html = response.data;

        // Check if Shopify
        if (!isShopifyStore(html)) {
            return res.status(200).json({
                success: true,
                data: {
                    url: targetUrl,
                    isShopify: false,
                    theme: null,
                    confidence: 0,
                    hasCustomizations: false,
                    timestamp: new Date().toISOString(),
                    message: 'Not a Shopify store'
                }
            });
        }

        // Detect theme
        const themeResult = detectTheme(html);

        res.status(200).json({
            success: true,
            data: {
                url: targetUrl,
                isShopify: true,
                theme: themeResult.theme,
                confidence: themeResult.confidence,
                themeStoreLink: themeLinks[themeResult.theme] || null,
                hasCustomizations: false,
                timestamp: new Date().toISOString(),
                message: `Detected Shopify store using ${themeResult.theme} theme`
            }
        });

    } catch (error) {
        console.error('Detection error:', error.message);
        res.status(500).json({
            success: false,
            error: 'Detection failed: ' + error.message
        });
    }
};
